# Generated by Django 5.0.3 on 2024-03-11 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('region', models.CharField(max_length=100)),
                ('emblem', models.ImageField(upload_to='')),
                ('management', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('emblem', models.ImageField(upload_to='')),
                ('management', models.TextField()),
                ('region', models.CharField(max_length=100)),
                ('federation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.federation')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('region', models.CharField(max_length=100)),
                ('management', models.TextField()),
                ('class_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.classevent')),
                ('federation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.federation')),
                ('type_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.typeevent')),
            ],
        ),
    ]
